name: fluttertencentplayer
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  # 应用包信息
  package_info: ^0.4.0+14
  # 设备信息
  device_info: ^0.4.1+5
  # 网络信息
  connectivity: ^0.4.8+1
  # 电池信息
  battery: ^0.3.1+8
  # 轻量级数据存储（kv存储）
  shared_preferences: ^0.5.6+2
  # 文件管理
  path_provider: ^1.6.5
  # 权限管理
  permission_handler: ^4.2.0+hotfix.3
  # 状态管理库
  provider: ^4.0.4
  # 全局事件总线
  event_bus: ^1.1.1
  # 加密库，SHA-1，SHA-224，SHA-256，SHA-384，SHA-512，MD5，HMAC (i.e. HMAC-MD5, HMAC-SHA1, HMAC-SHA256)
  crypto: any
  # 打开第三方应用，包含系统sms，call
  url_launcher: ^5.4.2
  # 屏幕适配方案
  flutter_screenutil: ^1.0.2
  # 下拉刷新
  pull_to_refresh: ^1.5.8
  # toast插件
  fluttertoast: ^3.1.3
  # 加载层
  flutter_svprogresshud: ^0.0.3
  # webView插件
  flutter_webview_plugin: ^0.3.10+1
  # 网络图片缓存
  cached_network_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
